# Generated by Django 4.0.4 on 2022-05-10 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examples', '0002_alter_example_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_examples', to=settings.AUTH_USER_MODEL),
        ),
    ]
