# Generated by Django 4.0.4 on 2022-05-11 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_sequencelabelingproject_use_relation'),
        ('examples', '0003_example_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_examples', to='projects.member'),
        ),
    ]
