# Generated by Django 4.0.4 on 2022-05-15 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_sequencelabelingproject_use_relation'),
        ('examples', '0004_alter_example_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='example',
            name='assigned_to_annotator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_annotation_examples', to='projects.member'),
        ),
        migrations.AddField(
            model_name='example',
            name='assigned_to_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_approval_examples', to='projects.member'),
        ),
    ]
