# Generated by Django 4.0.4 on 2022-05-22 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examples', '0005_remove_example_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplestate',
            name='approved_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='examplestate',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
